# Generated by Django 4.2.27 on 2026-01-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_response_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
