# Generated by Django 4.2.27 on 2026-01-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_question_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='background_color',
            field=models.CharField(default='#F8FAFC', max_length=7),
        ),
        migrations.AddField(
            model_name='form',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='forms/backgrounds/'),
        ),
        migrations.AddField(
            model_name='form',
            name='logo_image',
            field=models.ImageField(blank=True, null=True, upload_to='forms/logos/'),
        ),
        migrations.AddField(
            model_name='form',
            name='primary_color',
            field=models.CharField(default='#6366F1', max_length=7),
        ),
    ]
