# Generated by Django 4.2.27 on 2026-01-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_form_background_color_form_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='allow_multiple_responses',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='form',
            name='email_body',
            field=models.TextField(blank=True, help_text='Template for email body'),
        ),
        migrations.AddField(
            model_name='form',
            name='email_subject',
            field=models.CharField(blank=True, help_text='Template for email subject', max_length=255),
        ),
        migrations.AddField(
            model_name='form',
            name='notify_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='notify_respondent',
            field=models.BooleanField(default=False),
        ),
    ]
