# Generated by Django 4.2.27 on 2026-01-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='logo_alignment',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10),
        ),
    ]
