# Generated by Django 4.2.27 on 2026-01-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_form_logo_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='background_image',
            field=models.TextField(blank=True, help_text='URL to background image', null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='logo_image',
            field=models.TextField(blank=True, help_text='URL to logo image', null=True),
        ),
    ]
