# Generated by Django 4.2.27 on 2026-01-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_alter_form_background_image_alter_form_logo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Date when the form was first published', null=True),
        ),
    ]
