# Generated by Django 4.2.27 on 2026-01-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0010_form_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='slug',
            field=models.SlugField(blank=True, help_text='Custom URL identifier', max_length=255, null=True, unique=True),
        ),
    ]
