# Generated by Django 4.2.27 on 2026-01-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_form_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='expiry_at',
            field=models.DateTimeField(blank=True, help_text='Automatically close form at this time', null=True),
        ),
        migrations.AddField(
            model_name='form',
            name='inactive_message',
            field=models.TextField(default='This form is no longer accepting responses.', help_text='Message to show when inactive'),
        ),
        migrations.AddField(
            model_name='form',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Manual switch to open/close form'),
        ),
    ]
