# Generated by Django 4.2.27 on 2026-01-14 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0012_form_expiry_at_form_inactive_message_form_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_platform_admin',
            field=models.BooleanField(default=False, help_text='Grant full platform access'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='platform_status',
            field=models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_system', models.BooleanField(default=False, help_text='System roles cannot be deleted')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission')),
            ],
        ),
        migrations.CreateModel(
            name='FormCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='forms.form')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('form', 'user')},
            },
        ),
    ]
