# Generated by Django 4.2.27 on 2026-01-14 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0013_userprofile_is_platform_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'permissions': [('publish_form', 'Can publish form'), ('share_form', 'Can share form'), ('view_responses', 'Can view responses'), ('export_responses', 'Can export responses')]},
        ),
    ]
