# Generated by Django 4.2.27 on 2026-01-14 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0014_alter_form_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BLOCK_USER', 'Block User'), ('UNBLOCK_USER', 'Unblock User'), ('CREATE_ROLE', 'Create Role'), ('UPDATE_ROLE', 'Update Role'), ('DELETE_ROLE', 'Delete Role'), ('CHANGE_OWNERSHIP', 'Change Ownership'), ('LOGIN', 'Login'), ('OTHER', 'Other')], max_length=50)),
                ('target', models.CharField(help_text='Target object identifier', max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
