# Generated by Django 4.2.27 on 2026-01-15 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0016_userprofile_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormInvitee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitees', to='forms.form')),
            ],
            options={
                'unique_together': {('form', 'email')},
            },
        ),
    ]
